import type { Metadata } from 'next'
import { LEGAL_STYLE, shell } from '../LegalShell'

export const metadata: Metadata = {
  title: 'Borea — Terms of Use',
  description:
    'The terms under which Clarendon Labs LLC provides Borea: your licence, subscriptions and billing, what the coach is and is not, and the limits of our liability.',
  metadataBase: new URL('https://boreaapp.com'),
  alternates: { canonical: 'https://boreaapp.com/terms' },
}

const LEDE =
  'Plain English, no surprises. These terms cover your use of Borea for iPhone. If you do not agree with them, please do not use the app.'

const BODY = `
<div class="bl-callout">
  <strong>Read this part if you read nothing else.</strong> Borea is a nutrition tracking and
  coaching tool, not a medical device and not a doctor. Its coach is generated by an AI model and
  can be wrong. Nothing it says is medical advice. Talk to a qualified professional before making
  significant changes to your diet, especially if you are pregnant, under 18, or managing a medical
  condition or eating disorder.
</div>

<h2>1. Acceptance</h2>
<p>By downloading or using Borea you agree to these terms, which form an agreement between you and <strong>Clarendon Labs LLC</strong>, an Illinois limited liability company. If you use Borea on behalf of an organisation, you confirm you are authorised to accept on its behalf.</p>

<h2>2. Your licence</h2>
<p>We grant you a personal, non-exclusive, non-transferable, revocable licence to use Borea on Apple devices you own or control, as permitted by the App Store Terms of Service. You may not copy, decompile, reverse-engineer, resell, sublicense or attempt to extract the source of the app, except where that restriction is prohibited by law.</p>

<h2>3. Subscriptions and billing</h2>
<ul>
  <li><strong>Borea Pro</strong> is offered at <strong>$7.99 per month</strong> or <strong>$59.99 per year</strong>, with a <strong>7-day free trial</strong> for new subscribers. Prices may vary by region and are shown in the app before you purchase.</li>
  <li>Payment is taken by <strong>Apple</strong>, charged to your Apple Account at confirmation. We never see or handle your card details.</li>
  <li>Subscriptions <strong>renew automatically</strong> unless cancelled at least 24 hours before the end of the current period. Your account is charged for renewal within 24 hours of the period ending.</li>
  <li>You can <strong>manage or cancel</strong> at any time in Settings on your iPhone, under your Apple Account subscriptions. Cancelling stops the next renewal; it does not retroactively refund the current period.</li>
  <li>If you cancel a free trial before it ends, you are not charged. Any unused portion of a free trial is forfeited if you purchase a subscription during the trial.</li>
  <li><strong>Refunds</strong> are handled by Apple under its own policies, not by us. We will happily help you contact them.</li>
</ul>

<h2>4. The coach, and what it is not</h2>
<p>Borea&rsquo;s coaching, calorie estimates, macro targets and plans are generated with the help of AI models and on-device calculations. They are <strong>estimates and opinions, not facts and not medical advice</strong>.</p>
<ul>
  <li>Calorie and macro estimates from descriptions, photos or barcodes can be inaccurate. Weigh your food if precision matters to you.</li>
  <li>The coach can be confidently wrong. Treat it as a well-read training partner, not a clinician.</li>
  <li>Borea is not a medical device. It does not diagnose, treat, cure or prevent any condition.</li>
  <li>If you have or suspect a medical condition, an eating disorder, or are pregnant or breastfeeding, consult a qualified professional before following anything Borea suggests.</li>
</ul>
<p>You are responsible for decisions you make about your own diet and training.</p>

<h2>5. Acceptable use</h2>
<p>Don&rsquo;t use Borea to break the law, to attack or overload our servers, to attempt to extract other users&rsquo; data, or to automate access in ways that degrade the service for others. We may suspend access that does any of these.</p>

<h2>6. Your content</h2>
<p>Your log, photos and notes are yours. You keep all rights to them. We claim no ownership. When you use an AI feature, you grant us a limited licence to transmit and process that specific content solely to produce the response you asked for, as described in the <a href="/privacy">Privacy Policy</a>.</p>
<p>Transformation GIFs and videos you export are yours to share. They may include a Borea mark; you are free to share them anywhere, and you are responsible for what you choose to share.</p>

<h2>7. Availability</h2>
<p>We aim to keep Borea working, but we do not promise uninterrupted service. AI features depend on third-party providers and an internet connection, and may be unavailable, slow, or rate-limited. Core on-device tracking continues to work offline.</p>
<p>We may change, suspend or discontinue features. If we discontinue a paid feature materially, we will say so in the app.</p>

<h2>8. Disclaimer of warranties</h2>
<p>Borea is provided <strong>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</strong>, without warranties of any kind, whether express or implied, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement, to the fullest extent permitted by law.</p>

<h2>9. Limitation of liability</h2>
<p>To the fullest extent permitted by law, Clarendon Labs LLC is not liable for indirect, incidental, special, consequential or punitive damages, or for lost profits, data or goodwill, arising from your use of Borea. Our total liability for any claim relating to Borea is limited to the greater of the amount you paid us for Borea in the twelve months before the claim, or twenty-five US dollars.</p>
<p>Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you.</p>

<h2>10. Apple</h2>
<p>These terms are between you and Clarendon Labs LLC, not Apple. Apple has no obligation to provide support for Borea. Apple is a third-party beneficiary of these terms and may enforce them against you.</p>

<h2>11. Changes</h2>
<p>We may update these terms. The date at the top will change, and material changes will be announced in the app. Continuing to use Borea after a change means you accept the updated terms.</p>

<h2>12. Governing law</h2>
<p>These terms are governed by the laws of the State of Illinois, United States, without regard to its conflict-of-laws rules. Disputes will be brought in the state or federal courts located in Cook County, Illinois, unless applicable consumer law gives you the right to bring them elsewhere.</p>

<h2>13. Contact</h2>
<p><strong>Email:</strong> <a href="mailto:hello@clarendon.dev">hello@clarendon.dev</a><br/>
<strong>Mail:</strong> Clarendon Labs LLC &middot; 4801 N. Clarendon Ave. &middot; Chicago, IL 60640 &middot; United States</p>
`

export default function BoreaTerms() {
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: LEGAL_STYLE }} />
      <div dangerouslySetInnerHTML={{ __html: shell('Terms of Use', 'Version 1.0 · 10 August 2026', LEDE, BODY) }} />
    </>
  )
}
